
[functions.admin-users]
enabled = true
verify_jwt = true
import_map = "./functions/admin-users/deno.json"
entrypoint = "./functions/admin-users/index.ts"

[functions.push-subscribe]
enabled = true
verify_jwt = false
import_map = "./functions/push-subscribe/deno.json"
entrypoint = "./functions/push-subscribe/index.ts"

[functions.send-push]
enabled = true
verify_jwt = false
import_map = "./functions/send-push/deno.json"
entrypoint = "./functions/send-push/index.ts"
